import { Project, Task, User, Activity } from './types';

// Usuários mockados
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao@empresa.com',
    role: 'Admin',
    department: 'TI',
    workload: 40,
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria@empresa.com',
    role: 'Gerente',
    department: 'Projetos',
    workload: 40,
  },
  {
    id: '3',
    name: 'Pedro Costa',
    email: 'pedro@empresa.com',
    role: 'Colaborador',
    department: 'Desenvolvimento',
    workload: 40,
  },
  {
    id: '4',
    name: 'Ana Oliveira',
    email: 'ana@empresa.com',
    role: 'Colaborador',
    department: 'Design',
    workload: 30,
  },
  {
    id: '5',
    name: 'Carlos Mendes',
    email: 'carlos@cliente.com',
    role: 'Cliente',
    department: 'Externo',
    workload: 0,
  },
];

// Projetos mockados
export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Sistema de E-commerce',
    description: 'Desenvolvimento de plataforma de vendas online',
    client: 'Loja ABC',
    startDate: '2026-01-15',
    endDate: '2026-06-30',
    status: 'Em execução',
    progress: 45,
    teamMembers: ['2', '3', '4'],
    responsible: '2',
    budget: 150000,
    actualCost: 67500,
  },
  {
    id: '2',
    name: 'App Mobile Delivery',
    description: 'Aplicativo de entrega de alimentos',
    client: 'RestaurantesApp',
    startDate: '2026-02-01',
    endDate: '2026-05-31',
    status: 'Em execução',
    progress: 30,
    teamMembers: ['2', '3'],
    responsible: '2',
    budget: 80000,
    actualCost: 24000,
  },
  {
    id: '3',
    name: 'Portal Corporativo',
    description: 'Intranet para comunicação interna',
    client: 'Empresa XYZ',
    startDate: '2025-10-01',
    endDate: '2026-01-31',
    status: 'Concluído',
    progress: 100,
    teamMembers: ['3', '4'],
    responsible: '2',
    budget: 50000,
    actualCost: 48000,
  },
  {
    id: '4',
    name: 'Sistema CRM',
    description: 'Customer Relationship Management',
    client: 'Vendas Pro',
    startDate: '2026-03-01',
    endDate: '2026-08-31',
    status: 'Planejamento',
    progress: 10,
    teamMembers: ['2'],
    responsible: '2',
    budget: 120000,
    actualCost: 12000,
  },
];

// Tarefas mockadas
export const mockTasks: Task[] = [
  {
    id: '1',
    projectId: '1',
    title: 'Implementar carrinho de compras',
    description: 'Criar funcionalidade completa do carrinho com cálculo de frete',
    assignee: '3',
    dueDate: '2026-03-15',
    priority: 'Alta',
    status: 'Em progresso',
    progress: 60,
    dependencies: [],
    subtasks: [
      { id: 's1', title: 'Criar componente do carrinho', completed: true },
      { id: 's2', title: 'Integrar API de frete', completed: true },
      { id: 's3', title: 'Adicionar validações', completed: false },
    ],
    comments: [
      {
        id: 'c1',
        userId: '3',
        userName: 'Pedro Costa',
        content: 'Implementação do componente concluída',
        createdAt: '2026-02-08T10:30:00',
      },
    ],
    attachments: [],
    estimatedHours: 40,
    actualHours: 24,
  },
  {
    id: '2',
    projectId: '1',
    title: 'Design da página de produto',
    description: 'Criar layout responsivo para exibição de produtos',
    assignee: '4',
    dueDate: '2026-02-20',
    priority: 'Alta',
    status: 'Concluído',
    progress: 100,
    dependencies: [],
    subtasks: [],
    comments: [],
    attachments: [],
    estimatedHours: 20,
    actualHours: 18,
  },
  {
    id: '3',
    projectId: '1',
    title: 'Integração com gateway de pagamento',
    description: 'Implementar pagamento via cartão e PIX',
    assignee: '3',
    dueDate: '2026-03-30',
    priority: 'Urgente',
    status: 'A fazer',
    progress: 0,
    dependencies: ['1'],
    subtasks: [],
    comments: [],
    attachments: [],
    estimatedHours: 30,
    actualHours: 0,
  },
  {
    id: '4',
    projectId: '2',
    title: 'Tela de login do restaurante',
    description: 'Criar autenticação para parceiros',
    assignee: '3',
    dueDate: '2026-02-25',
    priority: 'Média',
    status: 'Em progresso',
    progress: 40,
    dependencies: [],
    subtasks: [],
    comments: [],
    attachments: [],
    estimatedHours: 16,
    actualHours: 8,
  },
  {
    id: '5',
    projectId: '2',
    title: 'Sistema de rastreamento em tempo real',
    description: 'GPS tracking para entregas',
    assignee: '3',
    dueDate: '2026-04-15',
    priority: 'Alta',
    status: 'Bloqueado',
    progress: 5,
    dependencies: ['4'],
    subtasks: [],
    comments: [],
    attachments: [],
    estimatedHours: 50,
    actualHours: 2,
  },
];

// Atividades recentes
export const mockActivities: Activity[] = [
  {
    id: 'a1',
    type: 'task_updated',
    userId: '3',
    userName: 'Pedro Costa',
    description: 'atualizou a tarefa "Implementar carrinho de compras"',
    timestamp: '2026-02-10T09:30:00',
    relatedId: '1',
  },
  {
    id: 'a2',
    type: 'comment_added',
    userId: '2',
    userName: 'Maria Santos',
    description: 'comentou em "Design da página de produto"',
    timestamp: '2026-02-10T08:15:00',
    relatedId: '2',
  },
  {
    id: 'a3',
    type: 'task_created',
    userId: '2',
    userName: 'Maria Santos',
    description: 'criou a tarefa "Integração com gateway de pagamento"',
    timestamp: '2026-02-09T16:45:00',
    relatedId: '3',
  },
  {
    id: 'a4',
    type: 'status_changed',
    userId: '4',
    userName: 'Ana Oliveira',
    description: 'moveu "Design da página de produto" para Concluído',
    timestamp: '2026-02-09T14:20:00',
    relatedId: '2',
  },
  {
    id: 'a5',
    type: 'file_attached',
    userId: '4',
    userName: 'Ana Oliveira',
    description: 'anexou arquivo em "Design da página de produto"',
    timestamp: '2026-02-08T11:30:00',
    relatedId: '2',
  },
];
